name: CI/CD

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest # 우분투 최신 버전으로 작업
    steps: # 순서대로 실행
      - name: 저장소 checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: "adopt"

      - name: Make properties
        run: |
          cd ./src/main/resources
          touch ./application-cicd.yml
          echo "${{ secrets.PROPERTIES }}" > ./application-cicd.yml

      - name: yml 업로드
        uses: actions/upload-artifact@v3.1.2
        with:
          name: application-cicd.yml
          path: ./src/main/resources/

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKER_REPO }} .

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub push
        run: docker push ${{ secrets.DOCKER_REPO }}

      - name: Send to deploy.sh
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          port: 22
          source: "./deploy.sh"
          target: "/home/ubuntu/"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            docker stop ${{ secrets.CONTAINER_NAME }}
            docker rm ${{ secrets.CONTAINER_NAME }}
            docker image rm $(docker images -q)
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            chmod 777 ./deploy.sh
            ./deploy.sh
#            docker run -d --name ${{ secrets.CONTAINER_NAME }} -p 8080:8080 ${{ secrets.DOCKER_REPO }}
            docker image prune -f
